<a target="_blank" href="https://colab.research.google.com/github/BrunoCapron/EQE358-metodos_numericos/blob/main/Capitulo_4_sistema_eq_linear/Metodos_iterativos.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

Resolução de sistemas de equações lineares por métodos iterativos

In [41]:
import numpy as np

def Jacobi(A, b, x0, num_it):
  n = b.size
  x_old = x0
  x_new = np.zeros(n)
  for k in range(num_it):
    for i in range(n):
      s = 0
      for j in range(n):
        if i != j:
          s = s + A[i, j] * x_old[j]
      x_new[i] = (b[i] - s) / A[i, i]
    x_old = x_new
  return x_new



def SOR(A, b, x, w, num_it):
  n = b.size
  for k in range(num_it):
    for i in range(n):
      s = 0
      for j in range(n):
        if i != j:
          s = s + A[i, j] * x0[j]
      x_gs = (b[i] - s) / A[i, i]
      x[i] = x[i] + w * (x_gs - x[i])
  return x

def gauss_seidel(A, b, x, num_it):
  n = b.size
  for k in range(num_it):
    for i in range(n):
      s = 0
      for j in range(n):
        if i != j:
          s = s + A[i, j] * x[j]
      x[i] = (b[i] - s) / A[i, i]
  return x

# resolução usando o solver do numpy
A = np.array([[5, -3, 0],
              [-2, 5, -3],
              [0, -2, 5]])
b = np.array([1, 1, 1])
print('Com o solver do numpy:')
x = np.linalg.solve(A, b)
print(x)

num_it = 10
x0 = np.zeros(b.size)

# resolução com o método de Jacobi
print('com Jacobi')
x1 = Jacobi(A, b, x0, num_it)
print(x1)

# resolução com o método de Gauss_Seidel
x0 = np.zeros(b.size)
print('com Gauss-Seidel')
x2 = gauss_seidel(A, b, x0, num_it)
print(x2)

# resolução com o método de Gauss_Seidel
x0 = np.zeros(b.size)
w = 1.2
print('com SOR')
x3 = SOR(A, b, x0, w, num_it)

print(x3)




Com o solver do numpy:
[0.66153846 0.76923077 0.50769231]
com Jacobi
[0.66040696 0.76832556 0.50733023]
com Gauss-Seidel
[0.66071129 0.76856903 0.50742761]
com SOR
[0.66153794 0.76923053 0.50769224]
